### ISSUE TITLE
Redundant Task

### ISSUE THREAD

**Issue by lih666** [roystormstout/DopeAF1#9]
Currently I make two copies of task. One for user task list, one for course list. Need to update.

**Comment by roystormstout** [comment]
Why don't you put the task in a class and then store the ids in both user and class class?

**Comment by lih666** [comment]
如果用户单独打开自己CSE110这个类别的task，我们怎么查找？n^2复杂度了兄弟

**Comment by roystormstout** [comment]
o(n)啊。在用户里的task list里面检查所有是cse110 class的task

**Comment by roystormstout** [comment]
同是o(n)存在外面比较space efficient.

**Comment by lih666** [comment]
How is this going?

**Comment by roystormstout** [comment]
I have put the task element outside, so it's finished.
